In [34]:
import numpy as np
import pandas as pd

In [35]:
np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

In [36]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2,cov_mat2,20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

In [37]:
df = pd.concat([df,df1],ignore_index=True)

In [38]:
df

    feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1
20  1.250737  0.186384  1.703624       0
21  0.731858  0.517441  2.244610       0
22  1.676860  4.187503 -0.080565       0
23  1.010229  1.437830  2.327788       0
24  0.748855  2.593111  1.170818       0
25  0.290746  0.866975  0.982643       0
26  0.898907  0.435960  0.820964       0
27  2.011059  1.920996  2.933090       0
28  0.204637 -0.011535  3.150780       0
29  1.425140  1.441152  0.182561       0
30  1.437892  1.099723  1.065406       0
31  2.224431  0.230401  1.192120       0
32 -0.723253  1.461259 -0.085367       0
33  2.823378 -0.332863  2.637391       0
34  0.177061 -0.598109  1.226512       0
35  1.233898  0.052778 -0.261576       0
36 -1.389866  0.666726  1.343517       0
37 -1.027861  1.131416  2.603234       0
38 -0.764314  1.566504  1.548788       0
39  0.384865  1.323546 -0.103193       0

In [39]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [40]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]

In [41]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [42]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [43]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [44]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [45]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

        PC1       PC2  target
0 -0.429384  0.829265       1
1 -1.124520  0.842226       1
2  0.599433  1.795862       1
3 -0.094556 -0.761566       1
4 -0.401542  1.203061       1